### ISSUE TITLE
OOTB otel component seems to have errors in default config

### ISSUE THREAD

**Issue by moxious** [grafana/agent-configurator#174] opened 2023-10-03 13:47 UTC
<img width="907" alt="image" src="https://github.com/grafana/agent-configurator/assets/5471710/f8975ffc-881a-4dc2-af54-60a2667e9947">

I am using an admittedly naive basic config from the tool (see below) - but this seems not to run as-is, even with the appropriate secrets.

```
module.git "grafana_cloud" {
  repository = "https://github.com/grafana/agent-modules.git"
  path = "modules/grafana-cloud/autoconfigure/module.river"
  revision = "main"
  pull_frequency = "0s"
  arguments {
    stack_name = "moxious"
    token = env("GRAFANA_CLOUD_TOKEN")
  }
}
otelcol.exporter.prometheus "to_prometheus" {
  forward_to = [
    module.git.grafana_cloud.exports.metrics_receiver,
  ]
}

otelcol.exporter.loki "to_loki" {
  forward_to = [
    module.git.grafana_cloud.exports.logs_receiver,
  ]
}

otelcol.receiver.otlp "default" {
  grpc {}
  http {}
  output {
    metrics = [otelcol.exporter.prometheus.to_prometheus.input]
    logs = [otelcol.exporter.loki.to_loki.input]
    traces = [module.git.grafana_cloud.exports.traces_receiver]
  }
}
```

**Comment by theSuess** [comment] 2023-10-05 06:52
Thanks for reporting this! The root cause of this issue is the usage of the [autoconfigure module](https://github.com/grafana/agent-modules/tree/main/modules/grafana-cloud/autoconfigure). This module talks to the grafana cloud api to fetch the prometheus, loki, and tempo URL as well as tenant IDs.

The advantage of this is, that the user does not have to collect all this information themselves. Drawback: the grafana cloud token needs the `stacks:read` scope.

I'll track implementation in #175 and close this issue!

**Closed by theSuess** 2023-10-05 06:52 UTC
